# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Test Instance
run-name: '[${{ github.event.client_payload.build_type }}] MMC instance of ${{ inputs.branch || github.event.client_payload.branch }}, triggered by @${{ github.event.client_payload.actor }}'
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Cleanroom branch'
        default: 'main'
  repository_dispatch:
    types: [cleanroom_upload_artifact]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script # run main.py
      run: python main.py
      env:
        cleanroomDownloadBranch: ${{ inputs.branch }}
        commit_hash: ${{ github.event.client_payload.commit_hash }}
        run_job_url: ${{ github.event.client_payload.run_job_url }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Cleanroom_MMC
        # A file, directory or wildcard pattern that describes what to upload
        path: build/output
